### ISSUE TITLE
Ability to crop/digital zoom image?

### ISSUE THREAD

**Issue by grantemsley** [easytarget/esp32-cam-webserver#173]
It looks like the espressif version is capable of doing this, if I'm reading this issue correctly: https://github.com/espressif/esp32-camera/issues/10

Is that available here, or could it be added in easily?

My use case: I have the camera mounted to the peephole of a door, so I can see who is standing outside. But because of the length of the peephole, only about 30% of the frame is useful, the rest just shows the metal tube. If it could just ignore the outside of the image, I'd get a clearer view, and maybe be able to run at a higher resolution for the part I care about.

Ideally 4 sliders, for crop top, bottom, left and right would let you adjust to only show the part of the image you care about.

**Comment by easytarget** [comment]
https://github.com/espressif/arduino-esp32/blob/ed53b6c8d47d7a0b38c9462dd209c30652268ebf/libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp#L1029

It's part of the 'official' example for the ESP2.x release.
This is one of a number of functions I'd like to port across, It shouldn't be too difficult since the architecture of both example is similar..  but I doubt if I'll have a chance to get at this anytime too but it is in the list now.
See:
https://github.com/easytarget/esp32-cam-webserver/discussions/167
