### ISSUE TITLE
Connecting to Wifi Network 0: [AC:84:C6:4A:98:DB] fast&furious  ...........Client connection Failed

### ISSUE THREAD

**Issue by arkadiusz-kopicinski** [easytarget/esp32-cam-webserver#177]
No matter which version I'm using I cannot connect my esp32-cam do home network . As AP using default setting it works fine on 192.168.4.1.

in myconfig.h I did

struct station stationList[] = {{"fast&furious", "my_password", true}};

5 networks found
  1 : [F8:1A:67:50:89:B8] fast&furious_ha (-55)
  2 : [AC:84:C6:4A:98:DB] fast&furious (-56)  -  Known!
  3 : [AE:E2:D3:FA:6D:F4] DIRECT-F4-HP OfficeJet 5200 (-74)
  4 : [00:72:63:5F:3B:EB] GreenFiber_M1465184 (-88)
  5 : [98:DA:C4:91:90:56] GreenFiber_R929062 (-96)
Connecting to Wifi Network 0: [AC:84:C6:4A:98:DB] fast&furious 
...........Client connection Failed

**Comment by zupermiez** [comment]
Ever found a solution to this?

**Comment by arkadiusz-kopicinski** [comment]
Yes, I've uploaded tasmota. Works everything what I need.

https://cgomesu.com/blog/Esp32cam-tasmota-webcam-server/

**Comment by easytarget** [comment]
:-)
The tasmota cam server is good, and the author puts quite a lot of effort into maintaining it; so that is actually quite a good choice

I am, however going to be extending the connection timeout in my code since this is probably what was affecting you, it's been affecting others, it's just too short by default.
