### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by Captainoddvious** [easytarget/esp32-cam-webserver#84]
As others have stated after some time (minutes to hours) the stream becomes unavailable and in some cases the main page also. (device still responds to pings)

I did find a post that suggests that a lot of the issue occur with chrome browser although I also experienced issues with IE and firefox (mobile and platform) Here is the fix they suggested. https://rntlab.com/question/solved-esp32-web-server-drops-connection-crashes/

Also would be really nice if there was the stream page also able to be changed from myconfig.h and a modified version that removed all the facial recognition.  Also debug is seems to be working intermittently.

I had to program my aithinker using the wrover option in board manager, not sure if this means mine was a clone.

Thanks again for the great project.

**Comment by easytarget** [comment]
Thanks!, one thing I am sure of is that there is no inherent issue within the code that causes streams to time-out or die from lack of resources, I have had streams last for days. The example you linked to is not really relevant to the way this sketch works. 

The jpeg 'stream' used here has to be requested frame-by-frame by your browser. What you are describing is consistent with intermittent network issues, the debug data lines are only generated in response to frame requests, so that indicates that the browser frame requests are not arriving. Look for the usual network suspects (power supply to ESP, range, etc..) 

Dropping Face recog. etc is in the works.

Renaming the viewer is a fine suggestion, but I'm unlikely to devote any time to it. Feel free to submit a PR, however.
