### ISSUE TITLE
stream ending unprompted... add auto-restart?

### ISSUE THREAD

**Issue by drunkscientist** [easytarget/esp32-cam-webserver#97]
so the board doesnt reset, it doesnt lose connection, it just stops the stream within 10 seconds or so of starting it. just blank with the little x in the corner. i dont get any errors on the debug just `
            MJPG: 4022B 32ms (31.2fps), AVG: 20ms (50.0fps), 0+0+0+0=0 0
                                                                        MJPG: 4041B fps), 0+0+0+0=0 0
                 Stream ended
`
so it can tell that the stream stopped, but i didnt tell it to stop and would very much like it to restart until i actually click stop. i can tolerate some lost frames here and there but i currently cant even enroll a face for testing before it drops. resolution and image quality make absolutely no difference whatsoever

**Comment by easytarget** [comment]
The 'stream ended' message indicates that the connection was dropped. Typically this is the network/browser timing out. 

The cam server never closes the connection itself (*), and although there could be errors elsewhere in the webcam code causing this, they are not apparent to me. I regularly stream for hours at a time with the two active cameras at my place.

(*) Seriously; there is no function in the code to close the connection. This confused the hell out of me at first..
Once a connection is made the stream server essentially [enters an infinite loop](https://github.com/easytarget/esp32-cam-webserver/blob/71db7b9da17d1a66a54631d1584fb251556db3b5/app_httpd.cpp#L398) responding to frame requests on the stream. To exit the loop it relies on the handler instance being killed, due to the connection timing out (handled by the ESP libraries) or being closed by the remote client.
- It *can* close the connection directly if the camera chip reports a failure, but that would result in different debug output.
